name: Nginx CD

on:
  push:
    paths:
      - 'nginx/**'
    branches: [ "main" ]
  pull_request:
    paths:
        - 'nginx/**'
    branches: [ "main" ]


# 테스트 결과 작성을 위해 쓰기권한 추가
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3


    # CD
    - name: Docker build & Push
      run: |
        docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }}:nginx ./nginx
        docker push ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }}:nginx

    - name: Deploy Images with Docker compose
      uses: appleboy/ssh-action@master
      env:
        APP: "santeut"
        COMPOSE: "/home/ec2-user/santeut/docker-compose.yml"
      with:
        username: ec2-user
        host: ${{ secrets.EC2_HOST }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        envs: APP, COMPOSE
        #script_stop: true
        script: |
          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker-compose -f $COMPOSE stop nginx-service
          sudo docker pull ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }}:nginx
          sudo docker-compose build --no-cache
          sudo docker-compose -f $COMPOSE up -d nginx-service
